apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prisma
  namespace: botium-box-ce
  labels:
    name: prisma
    app: botium-box-ce
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: prisma
        app: botium-box-ce
        tier: backend
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:1.34.10
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: botium-box-ce-configmap
                  key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: botium-box-ce
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma
    app: botium-box-ce